[db]
# Path to the DuckDB database file used to store repo documents and embeddings
duckdb_path = "repos.duckdb"

[together]
# Together.ai API key - recommended to be set in environment and loaded securely
# e.g. export TOGETHER_API_KEY="your_actual_api_key" (in .env)
embedding_model = "togethercomputer/m2-bert-80M-32k-retrieval"
llm_model = "togethercomputer/MoA-1-Turbo"

[ingestion]
# Root directory where your local cloned GitHub repos reside
repo_root_path = "/home/mjboothaus/code/github"
# Limit the number of repos to ingest; set to null to include all discovered
n_repo = 10
# List of subdirectories under repo_root_path to scan for repos
included_subdirs = ["databooth", "mjboothaus"]
# List of file extensions to include in ingestion; case-insensitive
file_types = [".py", ".md", ".rst"]

[logging]
# Log file path with rotation
log_file = "logs/rag_app.log"
log_level = "INFO"
rotation = "10 MB"
retention = "7 days"

[paths]
repo_root_path = "tests/sample_repos"
duckdb_db_path = "tests/test.duckdb"
cache_dir = "tests/cache_dir"

[provider]
name = "ollama" # "together" or "ollama"
embedding_model = "nomic-embed-text"
llm_model = "llama2"
